# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    branches: [ "master" ]
    inputs:
      ssh:
        description: 'ssh connection to actions'
        required: false
        default: 'false'

jobs:

  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Build
      id: blddx
      run: |
        cd $GITHUB_WORKSPACE
        ./build-release.sh
        echo "stat=succ" >> $GITHUB_OUTPUT

    - name: generate release tag
      id: tag
      if: steps.blddx.outputs.stat == 'succ' && (!cancelled())
      run: |
        sudo timedatectl set-timezone Asia/Shanghai
        echo -e "release_tag=$(date +"%Y.%m.%d-%H%M%S")" >> $GITHUB_OUTPUT
        touch release.txt
        echo -e "stat=success" >> $GITHUB_OUTPUT

    - name: push to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.stat == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ github.workspace }}/build/*.tar.gz